# Croptopia Botany Pots Compat mod file
modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="croptopiabotany"
version="${mod_version}"
displayName="${mod_name}"
description='''
Adds compatibility between Croptopia crops and Botany Pots. All Croptopia plants can now be grown in Botany Pots!
'''
authors="NotLucet"
logoFile="logo.png"
displayURL="https://github.com/NotLucet/croptopia-botany-pots-compat"
issueTrackerURL="https://github.com/NotLucet/croptopia-botany-pots-compat/issues"

[[dependencies.croptopiabotany]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.croptopiabotany]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.croptopiabotany]]
modId="botanypots"
type="required"
versionRange="[21.1,22)"
ordering="NONE"
side="BOTH"

[[dependencies.croptopiabotany]]
modId="croptopia"
type="required"
versionRange="[4.2,5)"
ordering="NONE"
side="BOTH"